src/hello-rails/config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/hello-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/hello-rails/app/models/visitor.rb
class Visitor < ApplicationRecord
end

src/hello-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

src/hello-rails/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:ip, :visits)
    end
end

src/hello-rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @ip = request.remote_ip
    visitor = Visitor.find_by(:ip => @ip)
    if visitor != nil
      visitor.visits =visitor.visits + 1
      visitor.save
    else
      visitor = Visitor.new
      visitor.ip = @ip
      visitor.visits = 1
      visitor.save
    end

    @visitors = Visitor.all
  end
end

src/hello-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

src/hello-rails/app/helpers/visitors_helper.rb
module VisitorsHelper
end

src/hello-rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

src/hello-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

src/hello-rails/app/views/visitors/_form.html.erb
<%= form_with(model: visitor, local: true) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip, id: :visitor_ip %>
  </div>

  <div class="field">
    <%= form.label :visits %>
    <%= form.number_field :visits, id: :visitor_visits %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/hello-rails/app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

src/hello-rails/app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitors</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th>Visits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.ip %></td>
        <td><%= visitor.visits %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

src/hello-rails/app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

src/hello-rails/app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @visitor.ip %>
</p>

<p>
  <strong>Visits:</strong>
  <%= @visitor.visits %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>

src/hello-rails/app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<p>Your ip is <%= @ip %></p>

<h2>Visitors</h2>

<table>
  <thead>
  <tr>
    <th>Ip</th>
    <th>Visits</th>
  </tr>
  </thead>

  <tbody>
  <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.ip %></td>
        <td><%= visitor.visits %></td>
      </tr>
  <% end %>
  </tbody>
</table>